---
title: "EPPS6356 Assignment 3"
author: "Seongdeok Oh"
date: "2022-09-28"
categories: [Data Visualization]
---

## Assignment 3

#### Compare the regression models

```{r}
## Data Visualization

rm(list=ls())
## Anscombe (1973) Quartlet

data("anscombe") # load Anscombe's data

# Create four model objects
lm1 <- lm(y1 ~ x1, data=anscombe)
lm2 <- lm(y2 ~ x2, data=anscombe)
lm3 <- lm(y3 ~ x3, data=anscombe)
lm4 <- lm(y4 ~ x4, data=anscombe)

## Fancy version (per help file)

ff <- y ~ x
mods <- setNames(as.list(1:4), paste0("lm", 1:4))

# Plot using for loop
for(i in 1:4) {
  ff[2:3] <- lapply(paste0(c("y","x"), i), as.name)
  ## or   ff[[2]] <- as.name(paste0("y", i))
  ##      ff[[3]] <- as.name(paste0("x", i))
  mods[[i]] <- lmi <- lm(ff, data = anscombe)
  print(anova(lmi))
}

```

```{r}
sapply(mods, coef)  # Note the use of this function
```

```{r}
lapply(mods, function(fm) coef(summary(fm)))
```

```{r}
# Preparing for the plots
op <- par(mfrow = c(2, 2), mar = 0.1+c(4,4,1,1), oma =  c(0, 0, 2, 0))

# Plot charts using for loop
for(i in 1:4) {
  ff[2:3] <- lapply(paste0(c("y","x"), i), as.name)
  plot(ff, data = anscombe, col = "orange", pch = 21, bg = "orange", cex = 1.2,
       xlim = c(3, 19), ylim = c(3, 13))
  abline(mods[[i]], col = "blue", lwd = 1.5)
}
mtext("Anscombe's 4 Regression data sets", outer = TRUE, cex = 1.5)
```

### Examples With Overfitting Finetune

```{r}
x <- seq(0, 2, by = 0.025)
y <- 5 + 3*x^2 + 100*x^3 + rnorm(length(x), 0, 50)
z <- x^2

set.seed(2022)

linearmodel <- lm(y ~ x) #model fitting

testx <- seq(1.1, 1.5, by = 0.025)
testy <- 5 + 3*testx^2 + 100*(testx)^3 + rnorm(length(testx), 0, 20)
predict_linear <- predict(linearmodel, list(x= testx)) #prediction on test data set

quadraticmodel <- lm(y~ x + z) #fitting
predict_quadratic = predict(quadraticmodel, list(x = testx, z = testx^2)) #prediction on test data set

smoothspline <- smooth.spline(x,y,df = 50) #fitting 
predict_spline <- predict(smoothspline, testx)$y #prediction on test data set

seq <- seq(min(x), max(x), by = 0.001)
predict <- predict(quadraticmodel, list(x = seq, z = seq^2))

par(mfrow=c(1,1))
plot(x,y, xlab = "X", ylab = "Y", main = "Example of Overfitting with finetune" )
abline(linearmodel, col = "blue", lwd = 1)
lines(seq,predict, col = "red", lwd = 2)
lines(smoothspline, col = "yellow", lwd = 2)
```

### Change Chart with ggplot2

```{r}
library(ggplot2)
ggplot(anscombe, aes(x=x4,y=y4)) + # create coordinate system
  geom_abline(col="blue") + # create line  with custom color
  geom_point(col="orange", lwd=3) + # create points with custom size and color
  xlab("x") + # change x label
  ylab("y") + # change y label
  scale_y_continuous(limits=c(2, 10)) + # change y axis limits
  scale_x_continuous(limits=c(4, 15))   # change x axis limits
```
